version: "3.9"

services:
  #order service:
  order:
    image: leebrouse7/order:latest
    container_name: order
    ports:
      - 5002:5002
      - 8283:8283
    depends_on:
      - stock
  #stock service:
  stock:
    image: leebrouse7/stock:latest
    container_name: stock
    ports:
      - 5003:5003
      - 8284:8284
  #payment service:
  payment:
    image: leebrouse7/payment:latest
    container_name: payment
    ports:
      - 5004:5004
      - 8285:8285
    depends_on:
      - order

  consul:
    image: hashicorp/consul
    command: agent -server -ui -node=serer-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - 8500:8500
      - 8600:8600/udp

  rabbit-mq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "6831:6831"
      - "16686:16686"
      - "14268:14268"
      - "4318:4318"
      - "4317:4317"
    environment:
      COLLECTOR_OTLP_ENABLED: true