name: Go CI/CD Pipeline

# whenever code is pushed to the main branch
on:
  push:
    branches:
      - main  # 可以改成你的默认分支，比如 master

jobs:
  # CI
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [order,stock,payment] # 你可以在这里添加更多的服务

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2' # 你的 Go 版本，可以改

      # - name: Run Tests
      #   run: go test ./... 调用command 用 run

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_NAME }}
          password: ${{secrets.DOCKER_HUB_SECRET }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./internal/${{ matrix.service }} # path is base on the root so it is ./go-hello-world
          file: ./internal/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_NAME }}/${{ matrix.service}}:latest