# 当特定 gRPC 服务未配置地址时，使用此默认地址
fallback-grpc-addr: localhost:3030
dial-grpc-timeout: 20

jaeger:
  url: "http://localhost:14268/api/traces"

consul:
  addr: localhost:8500

#Order Service
order:
  service-name: order
  server-to-run: http
#  has bug
  http-addr: localhost:8283 #original port on 8282
  grpc-addr: localhost:5002

# Stock Service
stock:
  service-name: stock
  server-to-run: grpc
  http-addr: localhost:8284 #original port on 8283
  grpc-addr: localhost:5003

# 为stripe做回调（webhook）
payment:
  service-name: payment
  server-to-run: http
  http-addr: localhost:8285 #original port on 8283
  grpc-addr: localhost:5004

rabbitmq:
  user: guest
  password: guest
  host: localhost
  port: 5672

#get the value from the environment valuable
stripe-key: "${STRIPE_KEY}"
endpoint-stripe-secret: "${ENDPOINT_STRIPE_SECRET}"